export type RiskLevelType = "Low" | "Medium" | "High";
export type InsuranceType = {
  protocol: string;
  iccr: number;
  ipi: string;
  claims: number;
  coverage: number;
  tvl: number;
  premiums: number;
  product_type:
    | "Smart Contract Cover"
    | "Smart Contract + Yield Cover"
    | "Audit Escrow + Risk Pools"
    | "Cross-Chain DeFi Cover"
    | "Reinsurance Pools"
    | "ETH Pool Cover"
    | "DeFi & DAO Cover"
    | "Gasless Coverage Pools"
    | "Legacy Cover Vaults"
    | "Stablecoin/Exchange Cover"
    | "Pay-as-you-go Cover"
    | "Flight Delay, Crop Insurance"
    | "Unified Coverage Index"
    | "Bond-based Claims Market"
    | "Derivatives Risk Cover";
  settlement_time: string;
  risk_level: RiskLevelType;
  rating: "AA+" | "AA" | "A+" | "A";
  payout_ratio: number;
  verified: boolean;
};

export const InsuranceData: InsuranceType[] = [
  {
    protocol: "Nexus Mutual",
    iccr: 89,
    ipi: "2.30",
    claims: 18200000,
    coverage: 165000000,
    tvl: 126000000,
    premiums: 31700000,
    product_type: "Smart Contract Cover",
    settlement_time: "10-14 days",
    risk_level: "Low",
    rating: "AA+",
    payout_ratio: 87,
    verified: true,
  },
  {
    protocol: "Risk Harbor",
    iccr: 89,
    ipi: "~2.2",
    claims: 2400000,
    coverage: 65000000,
    tvl: 65000000,
    premiums: 4900000,
    product_type: "Smart Contract + Yield Cover",
    settlement_time: "72 hours",
    risk_level: "Low",
    rating: "AA+",
    payout_ratio: 86,
    verified: true,
  },
  {
    protocol: "Sherlock",
    iccr: 85,
    ipi: "~2.4",
    claims: 3500000,
    coverage: 59300000,
    tvl: 42000000,
    premiums: 12000000,
    product_type: "Audit Escrow + Risk Pools",
    settlement_time: "7-14 days",
    risk_level: "Low",
    rating: "AA+",
    payout_ratio: 83,
    verified: true,
  },
  {
    protocol: "InsurAce",
    iccr: 82,
    ipi: "~2.7",
    claims: 8700000,
    coverage: 77000000,
    tvl: 46000000,
    premiums: 19000000,
    product_type: "Cross-Chain DeFi Cover",
    settlement_time: "7-10 days",
    risk_level: "Medium",
    rating: "AA",
    payout_ratio: 81,
    verified: true,
  },
  {
    protocol: "UnoRe",
    iccr: 71,
    ipi: "~3.0",
    claims: 0,
    coverage: 3790000,
    tvl: 3200000,
    premiums: 0,
    product_type: "Reinsurance Pools",
    settlement_time: "3 days",
    risk_level: "Medium",
    rating: "AA",
    payout_ratio: 69,
    verified: false,
  },
  {
    protocol: "Unslashed Finance",
    iccr: 78,
    ipi: "~2.8",
    claims: 1200000,
    coverage: 29000000,
    tvl: 21000000,
    premiums: 7800000,
    product_type: "ETH Pool Cover",
    settlement_time: "7-15 days",
    risk_level: "Medium",
    rating: "AA",
    payout_ratio: 78,
    verified: false,
  },
  {
    protocol: "Neptune Mutual",
    iccr: 82,
    ipi: "~2.5",
    claims: 3400000,
    coverage: 51000000,
    tvl: 39000000,
    premiums: 11000000,
    product_type: "DeFi & DAO Cover",
    settlement_time: "5-10 days",
    risk_level: "Low",
    rating: "AA",
    payout_ratio: 80,
    verified: true,
  },
  {
    protocol: "Ease",
    iccr: 75,
    ipi: "~2.6",
    claims: 890000,
    coverage: 5800000,
    tvl: 400000,
    premiums: 0,
    product_type: "Gasless Coverage Pools",
    settlement_time: "No active payouts",
    risk_level: "Medium",
    rating: "AA",
    payout_ratio: 75,
    verified: false,
  },
  {
    protocol: "Yinsure",
    iccr: 71,
    ipi: "~3.5",
    claims: 300000,
    coverage: 1800000,
    tvl: 100000,
    premiums: 0,
    product_type: "Legacy Cover Vaults",
    settlement_time: "2-6 days",
    risk_level: "Medium",
    rating: "A+",
    payout_ratio: 68,
    verified: false,
  },
  {
    protocol: "Bridge Mutual",
    iccr: 74,
    ipi: "~3.1",
    claims: 700000,
    coverage: 22000000,
    tvl: 14000000,
    premiums: 590000,
    product_type: "Stablecoin/Exchange Cover",
    settlement_time: "6 weeks",
    risk_level: "Medium",
    rating: "A+",
    payout_ratio: 70,
    verified: false,
  },
  {
    protocol: "Armor.fi",
    iccr: 71,
    ipi: "~2.9",
    claims: 1500000,
    coverage: 15000000,
    tvl: 7500000,
    premiums: 510000,
    product_type: "Pay-as-you-go Cover",
    settlement_time: "5-10 days",
    risk_level: "Medium",
    rating: "A+",
    payout_ratio: 72,
    verified: false,
  },
  {
    protocol: "Etherisc",
    iccr: 76,
    ipi: "~2.8",
    claims: 2100000,
    coverage: 17900000,
    tvl: 1200000,
    premiums: 870000,
    product_type: "Flight Delay, Crop Insurance",
    settlement_time: "some minutes",
    risk_level: "Medium",
    rating: "A+",
    payout_ratio: 77,
    verified: false,
  },
  {
    protocol: "OpenCover",
    iccr: 81,
    ipi: "~2.3",
    claims: 3100000,
    coverage: 32000000,
    tvl: 22000000,
    premiums: 920000,
    product_type: "Unified Coverage Index",
    settlement_time: "2-6 days",
    risk_level: "Low",
    rating: "AA",
    payout_ratio: 82,
    verified: true,
  },
  {
    protocol: "Cover Protocol (legacy)",
    iccr: 49,
    ipi: "~4.2",
    claims: 600000,
    coverage: 10000000,
    tvl: 1000000,
    premiums: 140000,
    product_type: "Bond-based Claims Market",
    settlement_time: "10-21 days",
    risk_level: "High",
    rating: "A",
    payout_ratio: 50,
    verified: false,
  },
  {
    protocol: "Opium Protocol",
    iccr: 67,
    ipi: "~3.4",
    claims: 1900000,
    coverage: 24000000,
    tvl: 2000000,
    premiums: 640000,
    product_type: "Derivatives Risk Cover",
    settlement_time: "some minutes",
    risk_level: "High",
    rating: "A",
    payout_ratio: 65,
    verified: false,
  },
];
